name       : libgravatar
version    : 18.04.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/libgravatar-18.04.0.tar.xz : 01676ca011254130bf29ef2bd0ff546b7fed80871786b7ce907736a6caddeef3
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : KDE PIM library providing Gravatar support.
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
