name       : libgravatar
version    : 20.08.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/libgravatar-20.08.1.tar.xz : dfe95055869944b79b1f4120f013b547225b02b69c7e410fd09d52469a892263
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - ktextwidgets-devel
    - pimcommon-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
