name       : libgravatar
version    : 19.04.2
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/libgravatar-19.04.2.tar.xz : e674fb2d80e341d569ac60eb6a3b516a71ddfba11c492fbcc21e61f823c07369
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
