name       : libgravatar
version    : 17.12.1
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/libgravatar-17.12.1.tar.xz : 982fee329cf7eae5c065772064c326643c83191bb23176f6bd501cb15db51d6c
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM library providing Gravatar support.
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
