name       : libgravatar
version    : 20.04.3
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/libgravatar-20.04.3.tar.xz : 0a5eadd5c8492eb17225e0ff2d221f69231e72ca9b8a78080301639662a18acf
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - ktextwidgets-devel
    - pimcommon-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
