name       : libgravatar
version    : 19.08.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/libgravatar-19.08.0.tar.xz : f8dd753abdc868623b878433c0b2ed53d4d4ab2cb62c69cb94c433e51cb713a9
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
