name       : libgravatar
version    : 18.12.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/libgravatar-18.12.0.tar.xz : 2411685662143f7c8be9c9a1944a3f406b6db23b5c162cdeafe76cf1f49df81c
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
