name       : libgravatar
version    : 18.04.1
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/libgravatar-18.04.1.tar.xz : 32db3eac65cab9a2dabb737f8984aedb10a7461b7b642acbeb6a19e8c161b9a7
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : KDE PIM library providing Gravatar support.
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
