name       : libgravatar
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/libgravatar-17.08.2.tar.xz : 6137334527aced1a17baf183d66ad5264b04fb06fbf334d2a344f53ebd8c5d7f
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : KDE PIM library providing Gravatar support.
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
