name       : libgravatar
version    : 19.08.3
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/libgravatar-19.08.3.tar.xz : 7f3421d1074065221e7ff892ba5f32614aef08b9ee407b5d8301e20f414bf8fb
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
