name       : libgravatar
version    : 23.04.2
release    : 65
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/libgravatar-23.04.2.tar.xz : 760077d270bc17ce7bcad9e498b7ce041200d8cedd136655a387df660783538f
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - kimap-devel
    - kio-devel
    - kpimtextedit-devel
    - ktextaddons-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
