name       : libgravatar
version    : 20.04.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/libgravatar-20.04.0.tar.xz : 6bc01e6c4d7b64c2ff7ea7fc33f45d9c0efa29147b0990f1b2658cc460af09d2
homepage   : https://kde.org/
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - ktextwidgets-devel
    - pimcommon-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
