name       : libgravatar
version    : 18.12.3
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/libgravatar-18.12.3.tar.xz : c44c139fbaffda352f0fe461065622cff65b6f1cc13cee8a0137acb27de143ee
license    :
    - GPL-2.0-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : KDE PIM library providing Gravatar support
description: |
    KDE PIM library providing Gravatar support.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kimap-devel
    - kio-devel
    - kmime-devel
    - ktextwidgets-devel
    - pimcommon-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
